### Environment

In [63]:
import pandas as pd

teams = pd.read_csv('mastering_ncaat_teams_historical.csv')
teams = teams[teams['year']>=2015]
# Filter 2019 for the 5 year data
#teams = teams[teams['year']>=2019]
teams = teams[['team_id', 'kenpom_id', 'torvik_id', 'miya_id']]
print(teams.shape)
teams.head()

(680, 4)

,team_id,kenpom_id,torvik_id,miya_id
727,2015 Duke,2015 Duke,2015 Duke,2015 Duke
728,2015 Kentucky,2015 Kentucky,2015 Kentucky,2015 Kentucky
729,2015 Michigan St.,2015 Michigan St.,2015 Michigan St.,2015 Michigan State
730,2015 Wisconsin,2015 Wisconsin,2015 Wisconsin,2015 Wisconsin
731,2015 Arizona,2015 Arizona,2015 Arizona,2015 Arizona

### Kenpom

In [64]:
ratings = pd.read_csv('raw_kenpom_ratings_historical.csv')
ratings['kenpom_id'] = ratings['Season'].astype(str) + ' ' + ratings['TeamName']
ratings = ratings[['kenpom_id', 'AdjEM', 'AdjOE', 'AdjDE', 'OE', 'DE', 'Tempo', 'AdjTempo']]
print('Ratings: ', ratings.shape)

roster = pd.read_csv('raw_kenpom_roster_historical.csv')
roster['kenpom_id'] = roster['Season'].astype(str) + ' ' + roster['TeamName']
roster = roster[['kenpom_id', 'HgtEff', 'Size', 'Exp', 'Bench']]
print('Roster: ', roster.shape)

Ratings:  (7950, 8)
Roster:  (6306, 5)

In [65]:
# Join the Kenpom tables for the 15 years models
print('Teams: ', teams.shape)
join_1 = pd.merge(teams, ratings, on='kenpom_id', how='inner')
print('Join Ratings: ', join_1.shape)
join_2 = pd.merge(join_1, roster, on='kenpom_id', how='inner')
print('Join Roster: ', join_2.shape)

Teams:  (680, 4)
Join Ratings:  (680, 11)
Join Roster:  (680, 15)

In [66]:
kenpom_df = join_2.rename(columns={
                             'AdjEM': 'kenpom_adjem',
                             'AdjOE': 'kenpom_adjoe',
                             'AdjDE': 'kenpom_adjde',
                             'OE': 'off_eff',
                             'DE': 'def_eff',
                             'Tempo': 'tempo',
                             'AdjTempo': 'adj_tempo',
                             'HgtEff' : 'height',
                             'Size': 'size',
                             'Exp': 'experience',
                             'Bench': 'bench'
})
kenpom_df.head()

,team_id,kenpom_id,torvik_id,miya_id,kenpom_adjem,kenpom_adjoe,kenpom_adjde,off_eff,def_eff,tempo,adj_tempo,height,size,experience,bench
0,2015 Duke,2015 Duke,2015 Duke,2015 Duke,29.3074,124.253,94.9453,120.499,97.7779,66.5735,65.6368,3.02,77.55,1.06,25.45
1,2015 Kentucky,2015 Kentucky,2015 Kentucky,2015 Kentucky,37.4333,121.270,83.8367,115.910,83.6596,63.8582,61.9696,6.89,79.28,0.73,39.90
2,2015 Michigan St.,2015 Michigan St.,2015 Michigan St.,2015 Michigan State,20.9213,115.973,95.0520,110.854,97.9100,63.1326,62.8407,-0.88,76.20,1.85,31.77
3,2015 Wisconsin,2015 Wisconsin,2015 Wisconsin,2015 Wisconsin,33.5251,126.815,93.2904,120.495,94.4646,59.2656,58.0767,5.05,79.17,2.08,21.24
4,2015 Arizona,2015 Arizona,2015 Arizona,2015 Arizona,32.3143,118.227,85.9123,113.625,87.4140,66.8428,65.5943,3.37,77.87,1.48,29.41

### Torvik

In [67]:
torvik = pd.read_csv('raw_torvik_teams_historical.csv')
torvik = torvik[['torvik_id', 'adj_oe', 'adj_de', 'barthag', 'wab',
                 'efg%', 'efgd%', 'ftr', 'ftrd', 'tor', 'tord', 'orb%', 'drb%',
                 'raw_tempo', '2p%', '2p%d', '3p%', '3p%d', 'blk%', 'blked%', 
                 'ast%', 'ast%d', '3pr', '3prd', 'adj_tempo', 'ft%', 'ft%d']]
print('Torvik: ', torvik.shape)
#splits = pd.read_csv('raw_torvik_splits_historical.csv')
#splits = splits[['torvik_id', 'off_dunk_fg%', 'off_dunk_share', 'off_close2_fg%', 'off_close2_share',
#                 'off_far2_fg%', 'off_far2_share', 'off_3pt_fg%', 'off_3pt_share', 
#                 'def_dunk_fg%', 'def_dunk_share', 'def_close2_fg%', 'def_close2_share',
#                 'def_far2_fg%', 'def_far2_share', 'def_3pt_fg%', 'def_3pt_share']]
#print('Splits: ', splits.shape)

Torvik:  (5960, 27)

In [68]:
print('KenPom: ', kenpom_df.shape)
df_15year = pd.merge(kenpom_df, torvik, on='torvik_id', how='inner')
print('15 Year DF: ', df_15year.shape)

KenPom:  (680, 15)
15 Year DF:  (680, 41)

In [69]:
df_15year.head()

,team_id,kenpom_id,torvik_id,miya_id,kenpom_adjem,kenpom_adjoe,kenpom_adjde,off_eff,def_eff,tempo,...,3p%d,blk%,blked%,ast%,ast%d,3pr,3prd,adj_tempo_y,ft%,ft%d
0,2015 Duke,2015 Duke,2015 Duke,2015 Duke,29.3074,124.253,94.9453,120.499,97.7779,66.5735,...,32.0,8.9,8.4,54.2,47.6,34.5,27.7,66.8,69.1,69.6
1,2015 Kentucky,2015 Kentucky,2015 Kentucky,2015 Kentucky,37.4333,121.270,83.8367,115.910,83.6596,63.8582,...,27.4,18.4,5.8,56.6,40.1,28.1,31.0,63.5,72.2,65.0
2,2015 Michigan St.,2015 Michigan St.,2015 Michigan St.,2015 Michigan State,20.9213,115.973,95.0520,110.854,97.9100,63.1326,...,32.3,13.2,7.3,64.6,50.5,34.7,35.3,64.1,63.3,71.7
3,2015 Wisconsin,2015 Wisconsin,2015 Wisconsin,2015 Wisconsin,33.5251,126.815,93.2904,120.495,94.4646,59.2656,...,36.0,9.2,5.9,50.2,40.7,37.0,26.7,59.3,76.3,68.1
4,2015 Arizona,2015 Arizona,2015 Arizona,2015 Arizona,32.3143,118.227,85.9123,113.625,87.4140,66.8428,...,32.8,10.2,6.3,53.2,49.0,25.8,31.4,66.9,69.9,69.2

### Miya

In [70]:
miya = pd.read_csv('raw_miya_ratings_historical.csv')
miya = miya[['miya_id', 'bpr', 'obpr', 'dbpr']]
print(miya.shape)
miya.head()

(4582, 4)

            miya_id        bpr       obpr       dbpr
0  2024 Connecticut  32.873291  19.151259  13.722032
1       2024 Purdue  28.473287  18.200035  10.273253
2       2024 Auburn  25.666839  13.924230  11.742609
3      2024 Houston  25.633417   9.882616  15.750801
4      2024 Arizona  25.276858  14.146493  11.130366

In [71]:
print('15 Year DF: ', df_15year.shape)
df_10year = pd.merge(df_15year, miya, on='miya_id', how='inner')
print('10 Year DF: ', df_10year.shape)

15 Year DF:  (680, 41)
10 Year DF:  (680, 44)

### Lineups

In [72]:
lineups = pd.read_csv('mastering_ncaat_lineups.csv')
lineups = lineups[['team_id', 'prpg!', 'dprpg', 'bpm', 'obpm', 'dbpm']]
print(lineups.shape)
lineups.head()

(680, 6)

            team_id  prpg!  dprpg   bpm  obpm  dbpm
0  2024 Connecticut   23.0   19.5  47.1  31.2  19.5
1     2015 Kentucky   14.2   20.6  45.0  21.2  22.5
2    2015 Wisconsin   24.2   21.4  44.9  32.7  18.3
3      2024 Houston   17.8   21.9  44.7  21.9  22.6
4      2021 Gonzaga   23.4   19.1  44.3  31.0  20.4

In [73]:
print('10 Year DF: ', df_10year.shape)
df_final = pd.merge(df_10year, lineups, on='team_id', how='inner')
print('Final DF: ', df_final.shape)

10 Year DF:  (680, 44)
Final DF:  (680, 49)

### Matchups

In [74]:
games = pd.read_csv('mastering_ncaat_games_historical.csv')
games = games[games['year']>=2015]
# Filter 2019 for the 5 year data
#teams = teams[teams['year']>=2019]
games = games[['game_id', 'year', 'region', 'round', 'high_bracket_seed', 'high_bracket_team', 'low_bracket_seed', 'low_bracket_team', 'win']]
print(games.shape)
games.head()

(565, 9)

,game_id,year,region,round,high_bracket_seed,high_bracket_team,low_bracket_seed,low_bracket_team,win
693,20151101,2015,Midwest,First Round,1,2015 Kentucky,16,2015 Hampton,1
694,20151102,2015,Midwest,First Round,8,2015 Cincinnati,9,2015 Purdue,1
695,20151103,2015,Midwest,First Round,5,2015 West Virginia,12,2015 Buffalo,1
696,20151104,2015,Midwest,First Round,4,2015 Maryland,13,2015 Valparaiso,1
697,20151105,2015,Midwest,First Round,6,2015 Butler,11,2015 Texas,1

In [75]:
matchups_1 = pd.merge(games, df_final, left_on='high_bracket_team', right_on='team_id', how='inner')
matchups_1 = matchups_1.drop(columns=['team_id', 'kenpom_id'])
print('High team matchup: ', matchups_1.shape)

High team matchup:  (565, 56)

In [76]:
matchups_1.columns.to_list()

['game_id',
 'year',
 'region',
 'round',
 'high_bracket_seed',
 'high_bracket_team',
 'low_bracket_seed',
 'low_bracket_team',
 'win',
 'torvik_id',
 'miya_id',
 'kenpom_adjem',
 'kenpom_adjoe',
 'kenpom_adjde',
 'off_eff',
 'def_eff',
 'tempo',
 'adj_tempo_x',
 'height',
 'size',
 'experience',
 'bench',
 'adj_oe',
 'adj_de',
 'barthag',
 'wab',
 'efg%',
 'efgd%',
 'ftr',
 'ftrd',
 'tor',
 'tord',
 'orb%',
 'drb%',
 'raw_tempo',
 '2p%',
 '2p%d',
 '3p%',
 '3p%d',
 'blk%',
 'blked%',
 'ast%',
 'ast%d',
 '3pr',
 '3prd',
 'adj_tempo_y',
 'ft%',
 'ft%d',
 'bpr',
 'obpr',
 'dbpr',
 'prpg!',
 'dprpg',
 'bpm',
 'obpm',
 'dbpm']

In [77]:
matchups_1 = matchups_1.rename(columns={
                             'kenpom_adjem': 'high_kenpom_adjem',
                             'kenpom_adjoe': 'high_kenpom_adjoe',
                             'kenpom_adjde': 'high_kenpom_adjde',
                             'off_eff': 'high_off_eff',
                             'def_eff': 'high_def_eff',
                             'height': 'high_height',
                             'size': 'high_size',
                             'experience': 'high_experience',
                             'bench': 'high_bench',
                             'adj_oe': 'high_barthag_oe',
                             'adj_de': 'high_barthag_de',
                             'barthag': 'high_barthag',
                             'wab': 'high_wab',
                             'efg%': 'high_efg%',
                             'efgd%': 'high_efgd%',
                             'ftr': 'high_ftr',
                             'ftrd': 'high_ftrd',
                             'tor': 'high_tor',
                             'tord': 'high_tord',
                             'orb%': 'high_orb%',
                             'drb%': 'high_drb%',
                             '2p%': 'high_2p%',
                             '2p%d': 'high_2p%d',
                             '3p%': 'high_3p%',
                             '3p%d': 'high_3p%d',
                             'blk%': 'high_blk%',
                             'blked%': 'high_blked%',
                             'ast%': 'high_ast%',
                             'ast%d': 'high_ast%d',
                             '3pr': 'high_3pr',
                             '3prd': 'high_3prd',
                             'ft%': 'high_ft%',
                             'ft%d': 'high_ft%d',
                             'bpr': 'high_bpr',
                             'obpr': 'high_obpr',
                             'dbpr': 'high_dbpr',
                             'prpg!': 'high_prpg!',
                             'dprpg': 'high_dprpg',
                             'bpm': 'high_bpm',
                             'obpm': 'high_obpm',
                             'dbpm': 'high_dbpm'                   
})

In [78]:
matchups_1['high_kenpom_adjde'] = 130 - matchups_1['high_kenpom_adjde']
matchups_1['high_def_eff'] = 130 - matchups_1['high_def_eff']
matchups_1['high_barthag_de'] = 130 - matchups_1['high_barthag_de']
matchups_1['high_efgd%'] = 100 - matchups_1['high_efgd%']
matchups_1['high_ftrd'] = 100 - matchups_1['high_ftrd']
matchups_1['high_tord'] = 100 - matchups_1['high_tord']
matchups_1['high_drb%'] = 100 - matchups_1['high_drb%']
matchups_1['high_2p%d'] = 100 - matchups_1['high_2p%d']
matchups_1['high_3p%d'] = 100 - matchups_1['high_3p%d']
matchups_1['high_blked%'] = 100 - matchups_1['high_blked%']
matchups_1['high_ast%d'] = 100 - matchups_1['high_ast%d']
matchups_1['high_3prd'] = 100 - matchups_1['high_3prd']
matchups_1['high_ft%d'] = 100 - matchups_1['high_ft%d']

In [83]:
matchups_2 = pd.merge(matchups_1, df_final, left_on='low_bracket_team', right_on='team_id', how='inner')
matchups_2 = matchups_2.drop(columns=['team_id', 'kenpom_id'])
print('Low team matchup: ', matchups_2.shape)

Low team matchup:  (565, 103)

In [84]:
matchups_2 = matchups_2.rename(columns={
                             'kenpom_adjem': 'low_kenpom_adjem',
                             'kenpom_adjoe': 'low_kenpom_adjoe',
                             'kenpom_adjde': 'low_kenpom_adjde',
                             'off_eff': 'low_off_eff',
                             'def_eff': 'low_def_eff',
                             'height': 'low_height',
                             'size': 'low_size',
                             'experience': 'low_experience',
                             'bench': 'low_bench',
                             'adj_oe': 'low_barthag_oe',
                             'adj_de': 'low_barthag_de',
                             'barthag': 'low_barthag',
                             'wab': 'low_wab',
                             'efg%': 'low_efg%',
                             'efgd%': 'low_efgd%',
                             'ftr': 'low_ftr',
                             'ftrd': 'low_ftrd',
                             'tor': 'low_tor',
                             'tord': 'low_tord',
                             'orb%': 'low_orb%',
                             'drb%': 'low_drb%',
                             '2p%': 'low_2p%',
                             '2p%d': 'low_2p%d',
                             '3p%': 'low_3p%',
                             '3p%d': 'low_3p%d',
                             'blk%': 'low_blk%',
                             'blked%': 'low_blked%',
                             'ast%': 'low_ast%',
                             'ast%d': 'low_ast%d',
                             '3pr': 'low_3pr',
                             '3prd': 'low_3prd',
                             'ft%': 'low_ft%',
                             'ft%d': 'low_ft%d',
                             'bpr': 'low_bpr',
                             'obpr': 'low_obpr',
                             'dbpr': 'low_dbpr',
                             'prpg!': 'low_prpg!',
                             'dprpg': 'low_dprpg',
                             'bpm': 'low_bpm',
                             'obpm': 'low_obpm',
                             'dbpm': 'low_dbpm'   
})

In [85]:
matchups_2['low_kenpom_adjde'] = 130 - matchups_2['low_kenpom_adjde']
matchups_2['low_def_eff'] = 130 - matchups_2['low_def_eff']
matchups_2['low_barthag_de'] = 130 - matchups_2['low_barthag_de']
matchups_2['low_efgd%'] = 100 - matchups_2['low_efgd%']
matchups_2['low_ftrd'] = 100 - matchups_2['low_ftrd']
matchups_2['low_tord'] = 100 - matchups_2['low_tord']
matchups_2['low_drb%'] = 100 - matchups_2['low_drb%']
matchups_2['low_2p%d'] = 100 - matchups_2['low_2p%d']
matchups_2['low_3p%d'] = 100 - matchups_2['low_3p%d']
matchups_2['low_blked%'] = 100 - matchups_2['low_blked%']
matchups_2['low_ast%d'] = 100 - matchups_2['low_ast%d']
matchups_2['low_3prd'] = 100 - matchups_2['low_3prd']
matchups_2['low_ft%d'] = 100 - matchups_2['low_ft%d']

In [86]:
matchups_2.columns.to_list()

['game_id',
 'year',
 'region',
 'round',
 'high_bracket_seed',
 'high_bracket_team',
 'low_bracket_seed',
 'low_bracket_team',
 'win',
 'torvik_id_x',
 'miya_id_x',
 'high_kenpom_adjem',
 'high_kenpom_adjoe',
 'high_kenpom_adjde',
 'high_off_eff',
 'high_def_eff',
 'tempo_x',
 'adj_tempo_x_x',
 'high_height',
 'high_size',
 'high_experience',
 'high_bench',
 'high_barthag_oe',
 'high_barthag_de',
 'high_barthag',
 'high_wab',
 'high_efg%',
 'high_efgd%',
 'high_ftr',
 'high_ftrd',
 'high_tor',
 'high_tord',
 'high_orb%',
 'high_drb%',
 'raw_tempo_x',
 'high_2p%',
 'high_2p%d',
 'high_3p%',
 'high_3p%d',
 'high_blk%',
 'high_blked%',
 'high_ast%',
 'high_ast%d',
 'high_3pr',
 'high_3prd',
 'adj_tempo_y_x',
 'high_ft%',
 'high_ft%d',
 'high_bpr',
 'high_obpr',
 'high_dbpr',
 'high_prpg!',
 'high_dprpg',
 'high_bpm',
 'high_obpm',
 'high_dbpm',
 'torvik_id_y',
 'miya_id_y',
 'low_kenpom_adjem',
 'low_kenpom_adjoe',
 'low_kenpom_adjde',
 'low_off_eff',
 'low_def_eff',
 'tempo_y',
 'adj_tempo_x_y',
 'low_height',
 'low_size',
 'low_experience',
 'low_bench',
 'low_barthag_oe',
 'low_barthag_de',
 'low_barthag',
 'low_wab',
 'low_efg%',
 'low_efgd%',
 'low_ftr',
 'low_ftrd',
 'low_tor',
 'low_tord',
 'low_orb%',
 'low_drb%',
 'raw_tempo_y',
 'low_2p%',
 'low_2p%d',
 'low_3p%',
 'low_3p%d',
 'low_blk%',
 'low_blked%',
 'low_ast%',
 'low_ast%d',
 'low_3pr',
 'low_3prd',
 'adj_tempo_y_y',
 'low_ft%',
 'low_ft%d',
 'low_bpr',
 'low_obpr',
 'low_dbpr',
 'low_prpg!',
 'low_dprpg',
 'low_bpm',
 'low_obpm',
 'low_dbpm']

In [87]:
matchups_df = matchups_2[['year',
                          'region',
                          'round',
                          'high_bracket_seed',
                          'high_bracket_team',
                          'low_bracket_seed',
                          'low_bracket_team',
                          'win']]
# Efficiency
matchups_df['wab'] = matchups_2['high_wab'] - matchups_2['low_wab']
matchups_df['prpg!'] = matchups_2['high_prpg!'] - matchups_2['low_dprpg']
matchups_df['dprpg'] = matchups_2['high_dprpg'] - matchups_2['low_prpg!']
matchups_df['bpm'] = matchups_2['high_bpm'] - matchups_2['low_bpm']
matchups_df['obpm'] = matchups_2['high_obpm'] - matchups_2['low_dbpm']
matchups_df['dbpm'] = matchups_2['high_dbpm'] - matchups_2['low_obpm']
matchups_df['bpr'] = matchups_2['high_bpr'] - matchups_2['low_bpr']
matchups_df['obpr'] = matchups_2['high_obpr'] - matchups_2['low_dbpr']
matchups_df['dbpr'] = matchups_2['high_dbpr'] - matchups_2['low_obpr']
matchups_df['kenpom_adjem'] = matchups_2['high_kenpom_adjem'] - matchups_2['low_kenpom_adjem']
matchups_df['kenpom_adjoe'] = matchups_2['high_kenpom_adjoe'] - matchups_2['low_kenpom_adjde']
matchups_df['kenpom_adjde'] = matchups_2['high_kenpom_adjde'] - matchups_2['low_kenpom_adjoe']
matchups_df['barthag'] = matchups_2['high_barthag'] - matchups_2['low_barthag']
matchups_df['barthag_oe'] = matchups_2['high_barthag_oe'] - matchups_2['low_barthag_de']
matchups_df['barthag_de'] = matchups_2['high_barthag_de'] - matchups_2['low_barthag_oe']
matchups_df['off_eff'] = matchups_2['high_off_eff'] - matchups_2['low_def_eff']
matchups_df['def_eff'] = matchups_2['high_def_eff'] - matchups_2['low_off_eff']
# Four Factors Offense
matchups_df['efg%'] = matchups_2['high_efg%'] - matchups_2['low_efgd%']
matchups_df['ftr'] = matchups_2['high_ftr'] - matchups_2['low_ftrd']
matchups_df['tor'] = matchups_2['high_tor'] - matchups_2['low_tord']
matchups_df['orb%'] = matchups_2['high_orb%'] - matchups_2['low_drb%']
# Four Factors Defense
matchups_df['efgd%'] = matchups_2['high_efgd%'] - matchups_2['low_efg%']
matchups_df['ftrd'] = matchups_2['high_ftrd'] - matchups_2['low_ftr']
matchups_df['tord'] = matchups_2['high_tord'] - matchups_2['low_tor']
matchups_df['drb%'] = matchups_2['high_drb%'] - matchups_2['low_orb%']
# Traditional Stats Offense
matchups_df['2p%'] = matchups_2['high_2p%'] - matchups_2['low_2p%d']
matchups_df['3p%'] = matchups_2['high_3p%'] - matchups_2['low_3p%d']
matchups_df['blked%'] = matchups_2['high_blked%'] - matchups_2['low_blk%']
matchups_df['ast%'] = matchups_2['high_ast%'] - matchups_2['low_ast%d']
matchups_df['3pr'] = matchups_2['high_3pr'] - matchups_2['low_3prd']
matchups_df['ft%'] = matchups_2['high_ft%'] - matchups_2['low_ft%d']
# Traditional Stats Defense
matchups_df['2p%d'] = matchups_2['high_2p%d'] - matchups_2['low_2p%']
matchups_df['3p%d'] = matchups_2['high_3p%d'] - matchups_2['low_3p%']
matchups_df['blk%'] = matchups_2['high_blk%'] - matchups_2['low_blked%']
matchups_df['ast%d'] = matchups_2['high_ast%d'] - matchups_2['low_ast%']
matchups_df['3prd'] = matchups_2['high_3prd'] - matchups_2['low_3pr']
matchups_df['ft%d'] = matchups_2['high_ft%d'] - matchups_2['low_ft%']
# Miscellaneous Stats
matchups_df['height'] = matchups_2['high_height'] - matchups_2['low_height']
matchups_df['size'] = matchups_2['high_size'] - matchups_2['low_size']
matchups_df['experience'] = matchups_2['high_experience'] - matchups_2['low_experience']
matchups_df['bench'] = matchups_2['high_bench'] - matchups_2['low_bench']

/var/folders/nd/7h3lcr8d2cjbxfmfqghczqz40000gn/T/ipykernel_68286/4095806133.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  matchups_df['wab'] = matchups_2['high_wab'] - matchups_2['low_wab']
/var/folders/nd/7h3lcr8d2cjbxfmfqghczqz40000gn/T/ipykernel_68286/4095806133.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  matchups_df['prpg!'] = matchups_2['high_prpg!'] - matchups_2['low_dprpg']
/var/folders/nd/7h3lcr8d2cjbxfmfqghczqz40000gn/T/ipykernel_68286/4095806133.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  matchups_df['dprpg'] = matchups_2['high_dprpg'] - matchups_2['low_prpg!']
/var/folders/nd/7h3lcr8d2cjbxfmfqghczqz40000gn/T/ipykernel_68286/4095806133.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  matchups_df['bpm'] = matchups_2['high_bpm'] - matchups_2['low_bpm']
/var/folders/nd/7h3lcr8d2cjbxfmfqghczqz40000gn/T/ipykernel_68286/4095806133.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  matchups_df['obpm'] = matchups_2['high_obpm'] - matchups_2['low_dbpm']
/var/folders/nd/7h3lcr8d2cjbxfmfqghczqz40000gn/T/ipykernel_68286/4095806133.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  matchups_df['dbpm'] = matchups_2['high_dbpm'] - matchups_2['low_obpm']
/var/folders/nd/7h3lcr8d2cjbxfmfqghczqz40000gn/T/ipykernel_68286/4095806133.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  matchups_df['bpr'] = matchups_2['high_bpr'] - matchups_2['low_bpr']
/var/folders/nd/7h3lcr8d2cjbxfmfqghczqz40000gn/T/ipykernel_68286/4095806133.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  matchups_df['obpr'] = matchups_2['high_obpr'] - matchups_2['low_dbpr']
/var/folders/nd/7h3lcr8d2cjbxfmfqghczqz40000gn/T/ipykernel_68286/4095806133.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  matchups_df['dbpr'] = matchups_2['high_dbpr'] - matchups_2['low_obpr']
/var/folders/nd/7h3lcr8d2cjbxfmfqghczqz40000gn/T/ipykernel_68286/4095806133.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  matchups_df['kenpom_adjem'] = matchups_2['high_kenpom_adjem'] - matchups_2['low_kenpom_adjem']
/var/folders/nd/7h3lcr8d2cjbxfmfqghczqz40000gn/T/ipykernel_68286/4095806133.py:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  matchups_df['kenpom_adjoe'] = matchups_2['high_kenpom_adjoe'] - matchups_2['low_kenpom_adjde']
/var/folders/nd/7h3lcr8d2cjbxfmfqghczqz40000gn/T/ipykernel_68286/4095806133.py:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  matchups_df['kenpom_adjde'] = matchups_2['high_kenpom_adjde'] - matchups_2['low_kenpom_adjoe']
/var/folders/nd/7h3lcr8d2cjbxfmfqghczqz40000gn/T/ipykernel_68286/4095806133.py:22: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  matchups_df['barthag'] = matchups_2['high_barthag'] - matchups_2['low_barthag']
/var/folders/nd/7h3lcr8d2cjbxfmfqghczqz40000gn/T/ipykernel_68286/4095806133.py:23: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  matchups_df['barthag_oe'] = matchups_2['high_barthag_oe'] - matchups_2['low_barthag_de']
/var/folders/nd/7h3lcr8d2cjbxfmfqghczqz40000gn/T/ipykernel_68286/4095806133.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  matchups_df['barthag_de'] = matchups_2['high_barthag_de'] - matchups_2['low_barthag_oe']
/var/folders/nd/7h3lcr8d2cjbxfmfqghczqz40000gn/T/ipykernel_68286/4095806133.py:25: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  matchups_df['off_eff'] = matchups_2['high_off_eff'] - matchups_2['low_def_eff']
/var/folders/nd/7h3lcr8d2cjbxfmfqghczqz40000gn/T/ipykernel_68286/4095806133.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  matchups_df['def_eff'] = matchups_2['high_def_eff'] - matchups_2['low_off_eff']
/var/folders/nd/7h3lcr8d2cjbxfmfqghczqz40000gn/T/ipykernel_68286/4095806133.py:28: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  matchups_df['efg%'] = matchups_2['high_efg%'] - matchups_2['low_efgd%']
/var/folders/nd/7h3lcr8d2cjbxfmfqghczqz40000gn/T/ipykernel_68286/4095806133.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  matchups_df['ftr'] = matchups_2['high_ftr'] - matchups_2['low_ftrd']
/var/folders/nd/7h3lcr8d2cjbxfmfqghczqz40000gn/T/ipykernel_68286/4095806133.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  matchups_df['tor'] = matchups_2['high_tor'] - matchups_2['low_tord']
/var/folders/nd/7h3lcr8d2cjbxfmfqghczqz40000gn/T/ipykernel_68286/4095806133.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  matchups_df['orb%'] = matchups_2['high_orb%'] - matchups_2['low_drb%']
/var/folders/nd/7h3lcr8d2cjbxfmfqghczqz40000gn/T/ipykernel_68286/4095806133.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  matchups_df['efgd%'] = matchups_2['high_efgd%'] - matchups_2['low_efg%']
/var/folders/nd/7h3lcr8d2cjbxfmfqghczqz40000gn/T/ipykernel_68286/4095806133.py:34: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  matchups_df['ftrd'] = matchups_2['high_ftrd'] - matchups_2['low_ftr']
/var/folders/nd/7h3lcr8d2cjbxfmfqghczqz40000gn/T/ipykernel_68286/4095806133.py:35: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  matchups_df['tord'] = matchups_2['high_tord'] - matchups_2['low_tor']
/var/folders/nd/7h3lcr8d2cjbxfmfqghczqz40000gn/T/ipykernel_68286/4095806133.py:36: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  matchups_df['drb%'] = matchups_2['high_drb%'] - matchups_2['low_orb%']
/var/folders/nd/7h3lcr8d2cjbxfmfqghczqz40000gn/T/ipykernel_68286/4095806133.py:38: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  matchups_df['2p%'] = matchups_2['high_2p%'] - matchups_2['low_2p%d']
/var/folders/nd/7h3lcr8d2cjbxfmfqghczqz40000gn/T/ipykernel_68286/4095806133.py:39: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  matchups_df['3p%'] = matchups_2['high_3p%'] - matchups_2['low_3p%d']
/var/folders/nd/7h3lcr8d2cjbxfmfqghczqz40000gn/T/ipykernel_68286/4095806133.py:40: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  matchups_df['blked%'] = matchups_2['high_blked%'] - matchups_2['low_blk%']
/var/folders/nd/7h3lcr8d2cjbxfmfqghczqz40000gn/T/ipykernel_68286/4095806133.py:41: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  matchups_df['ast%'] = matchups_2['high_ast%'] - matchups_2['low_ast%d']
/var/folders/nd/7h3lcr8d2cjbxfmfqghczqz40000gn/T/ipykernel_68286/4095806133.py:42: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  matchups_df['3pr'] = matchups_2['high_3pr'] - matchups_2['low_3prd']
/var/folders/nd/7h3lcr8d2cjbxfmfqghczqz40000gn/T/ipykernel_68286/4095806133.py:43: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  matchups_df['ft%'] = matchups_2['high_ft%'] - matchups_2['low_ft%d']
/var/folders/nd/7h3lcr8d2cjbxfmfqghczqz40000gn/T/ipykernel_68286/4095806133.py:45: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  matchups_df['2p%d'] = matchups_2['high_2p%d'] - matchups_2['low_2p%']
/var/folders/nd/7h3lcr8d2cjbxfmfqghczqz40000gn/T/ipykernel_68286/4095806133.py:46: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  matchups_df['3p%d'] = matchups_2['high_3p%d'] - matchups_2['low_3p%']
/var/folders/nd/7h3lcr8d2cjbxfmfqghczqz40000gn/T/ipykernel_68286/4095806133.py:47: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  matchups_df['blk%'] = matchups_2['high_blk%'] - matchups_2['low_blked%']
/var/folders/nd/7h3lcr8d2cjbxfmfqghczqz40000gn/T/ipykernel_68286/4095806133.py:48: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  matchups_df['ast%d'] = matchups_2['high_ast%d'] - matchups_2['low_ast%']
/var/folders/nd/7h3lcr8d2cjbxfmfqghczqz40000gn/T/ipykernel_68286/4095806133.py:49: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  matchups_df['3prd'] = matchups_2['high_3prd'] - matchups_2['low_3pr']
/var/folders/nd/7h3lcr8d2cjbxfmfqghczqz40000gn/T/ipykernel_68286/4095806133.py:50: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  matchups_df['ft%d'] = matchups_2['high_ft%d'] - matchups_2['low_ft%']
/var/folders/nd/7h3lcr8d2cjbxfmfqghczqz40000gn/T/ipykernel_68286/4095806133.py:52: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  matchups_df['height'] = matchups_2['high_height'] - matchups_2['low_height']
/var/folders/nd/7h3lcr8d2cjbxfmfqghczqz40000gn/T/ipykernel_68286/4095806133.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  matchups_df['size'] = matchups_2['high_size'] - matchups_2['low_size']
/var/folders/nd/7h3lcr8d2cjbxfmfqghczqz40000gn/T/ipykernel_68286/4095806133.py:54: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  matchups_df['experience'] = matchups_2['high_experience'] - matchups_2['low_experience']
/var/folders/nd/7h3lcr8d2cjbxfmfqghczqz40000gn/T/ipykernel_68286/4095806133.py:55: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  matchups_df['bench'] = matchups_2['high_bench'] - matchups_2['low_bench']

In [88]:
print(matchups_df.shape)
matchups_df.head()

(565, 49)

,year,region,round,high_bracket_seed,high_bracket_team,low_bracket_seed,low_bracket_team,win,wab,prpg!,...,2p%d,3p%d,blk%,ast%d,3prd,ft%d,height,size,experience,bench
0,2015,Midwest,First Round,1,2015 Kentucky,16,2015 Hampton,1,25.303699,5.0,...,15.0,42.2,-71.5,13.4,35.7,-30.2,7.80,3.43,-1.26,4.70
1,2015,Midwest,Second Round,1,2015 Kentucky,8,2015 Cincinnati,1,14.121427,-3.5,...,10.4,39.3,-73.6,6.8,38.4,-32.4,5.55,2.04,-0.71,6.33
2,2015,Midwest,Sweet 16,1,2015 Kentucky,5,2015 West Virginia,1,9.010267,-0.6,...,15.0,40.7,-71.7,2.7,35.2,-31.0,5.87,2.79,-0.63,-1.89
3,2015,Midwest,Elite Eight,1,2015 Kentucky,3,2015 Notre Dame,1,4.516254,-3.2,...,2.5,33.4,-74.9,5.5,30.4,-39.0,7.55,1.99,-1.04,20.34
4,2015,Midwest,Second Round,6,2015 Butler,3,2015 Notre Dame,0,-5.082442,-3.8,...,-5.7,30.2,-84.8,-5.0,27.5,-41.9,0.50,-0.20,0.22,1.61

In [89]:
matchups_df.columns.to_list()

['year',
 'region',
 'round',
 'high_bracket_seed',
 'high_bracket_team',
 'low_bracket_seed',
 'low_bracket_team',
 'win',
 'wab',
 'prpg!',
 'dprpg',
 'bpm',
 'obpm',
 'dbpm',
 'bpr',
 'obpr',
 'dbpr',
 'kenpom_adjem',
 'kenpom_adjoe',
 'kenpom_adjde',
 'barthag',
 'barthag_oe',
 'barthag_de',
 'off_eff',
 'def_eff',
 'efg%',
 'ftr',
 'tor',
 'orb%',
 'efgd%',
 'ftrd',
 'tord',
 'drb%',
 '2p%',
 '3p%',
 'blked%',
 'ast%',
 '3pr',
 'ft%',
 '2p%d',
 '3p%d',
 'blk%',
 'ast%d',
 '3prd',
 'ft%d',
 'height',
 'size',
 'experience',
 'bench']

In [90]:
matchups_df.to_csv('matchups_10.csv')